---
title: camila dexter
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: Fashion Designer & Stylist
description: Fashion Designer & Stylist based in Berlin
url: http://sergimiral.github.io
source: src
destination: dist
exclude:
- assets
author:
  name: Sergi Miral
  email: sergimiral@gmail.com
  uri: sergimiral.com
  bio: Designer &amp; Coder from Barcelona
  twitter: sergimiral
  github: sergimiral
future: true
show_drafts: true
lsi: false
limit_posts: 10
permalink: pretty
paginate: 10
paginate_path: page:num
excerpt_separator: "<!--more-->"
markdown: redcarpet
redcarpet:
  extensions:
  - no_intra_emphasis
  - tables
  - fenced_code_blocks
  - autolink
  - smart
  - strikethrough
  - superscript
  - underline
  - highlight
  - footnotes
highlighter: true
gems:
- jekyll-archives
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
jekyll-archives:
  enabled:
  - year
  - month
  - categories
  - tags
  layouts:
    year: year-archive
    month: month-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
    category: "/category/:name/"
    tags: "/tag/:name/"
